### ISSUE TITLE
:not-Selector also possible?

### ISSUE THREAD

**Issue by tliebig** [NeXTs/Jets.js#12]
Hey Den,

would it be possible to add support for the :not(selector)? That is, entering ":not('keyword')" would show all results that do not contain 'keyword'. CSS supports this natively, but I think the JS code would have to be updated for it to work...

**Comment by NeXTs** [comment]
Easy as that, Torsten!
Hi :D 

Update to v0.7.0 and use `invert` option

**Comment by tliebig** [comment]
Wow, that was quick :o)

Can this be changed on the fly? I'm using a standard search box where the user adds search terms simply by clicking on a link (which just gets written into the search box by JS and triggers the change event). Since the last search term ist "none of the before", the option would only need to be activated for this query, while staying disabled for any other query.

Or – if the above is not feasible – I'm quite fine with just prepending the term entered into the search box with something. Probably just with ":not('search_term')".

**Comment by NeXTs** [comment]
Nope, I do not see easy way to change it on the fly
