### ISSUE TITLE
add custom hiding method

### ISSUE THREAD

**Issue by flying-sheep** [NeXTs/Jets.js#20]
`display` is not animatable. so some use `height: 0` or `transform: scale(0)` or `opacity: 0`, or a combination of those, combined with `transition`

**Comment by NeXTs** [comment]
I had such idea but while working on it I noticed that it's resource-intensive operation for browser on big lists. Although I must admit it should be helpful for small lists

**Comment by flying-sheep** [comment]
and while on small lists you don’t need your speed-improving idea at all (the class approach suffices), it’s nice to have a unified interface.

**Comment by NeXTs** [comment]
So that I guess this issue can be considered exhausted?

It's impossible to implement smooth animation for big lists, at least as for now

**Comment by flying-sheep** [comment]
exhausted? i don’t understand, but i guess i said the opposite:

since using jets.js for small lists is a valid use case as well, this option is useful IMHO.

**Comment by NeXTs** [comment]
Ok, I'll think on how to implement it better

**Comment by flying-sheep** [comment]
Isn't that easy? Just add another option and do:

```js
var strictCSS = is_strict_selector ? '' : this.content_param + '>';
var hideCSS = this.options.hideCSS || 'display:none';
var importantCSS = this.options.addImportant ? '!important' : '';

var css_rule = strictCSS + selectors.join(is_strict_selector ? ',' : '') + '{' + hideCSS + importantCSS + '}';
```

**Comment by NeXTs** [comment]
@flying-sheep This was great idea, thank you!
I've called this option `hideBy`, added example and mentioned in docs.

btw there are some difficulties with animating table's rows-height in chrome. will investigate it later

**Comment by flying-sheep** [comment]
cool!

btw: you can e.g. do `hideBy: 'opacity: .5'` to only fade items instead of completely hiding them.

**Comment by NeXTs** [comment]
Yep this might be helpful for some cases too
