### ISSUE TITLE
Feature: Highlight input text

### ISSUE THREAD

**Issue by CheloXL** [NeXTs/Jets.js#23]
Hi, 
Not sure if this is possible with css only (probably not), but it would be nice if, on the filtered result, I get a highlight of the searched text, like:
![image](https://cloud.githubusercontent.com/assets/201414/17569044/e12fabe4-5f1c-11e6-8f26-17638a078b33.png)

**Comment by NeXTs** [comment]
Hi,

Standart solution to this task would be to wrap every "highlighed" word in some `<span>` and set background color to them. Though this is not CSS-only solution.

The closest CSS-only solution with no neet to wrap words in additional tags that I see is probably to generate tricky, complex background gradients. Using gradients you can do incredible things, see [Lea Verou's patterns gallery](http://lea.verou.me/css3patterns/). Of course you'll need to determine the positions of words that you want to highlight but it is as idea.

And, of course this technique is not compatible with Jets implementation as Jets's idea is - simply hide unnecessary rows.
