### ISSUE TITLE
Doesn't work with vuetable's ajax data

### ISSUE THREAD

**Issue by Lahori-Jawan** [NeXTs/Jets.js#24]
I am using [vuetable](https://github.com/ratiw/vue-table) and hence vuejs in my project. vuetable expects an endpoint for the data to display in table, so data is coming on the fly from server. when application is run and and i type first character, the whole table disappears i.e. `display: none;` after much hassle I noticed that in case of vuetable, `data-jets="<name>"` attribute is absent. I say so because I copied the same table on [jsfiddle](http://jsfiddle.net/t44hs75t/1/) with same js code and it works just as amazing as the plugin is. Or I m missing something here? See attached images for further details!

![fiddle](https://cloud.githubusercontent.com/assets/7579344/18680595/e33021b8-7f7d-11e6-9f6b-4b34e425cc7a.PNG)
![local](https://cloud.githubusercontent.com/assets/7579344/18680607/ee63cf3a-7f7d-11e6-858a-9becb2e31aa4.PNG)

**Comment by NeXTs** [comment]
Hi
I'm not familiar with vue or vuetable but I suppose it happens because you don't call `.update()` after vuetable changes DOM.
I need to see your code, at least at codepen

After appending rows / changing layout - you should call `jets.update()` manually so it will set those `data-jets` attributes

**Comment by Lahori-Jawan** [comment]
Thank you @NeXTs  following your directions i just achieved it. Thanks again!
just to let others know how i did it, since input is used to search the DOM, i used jquery to check as soon as the input is entered, the `jets.update(true)` should trigger and BOOM!!! it works great.

`$(document).ready(function() {`
         `var jets = new Jets({`
         `searchTag: '#jetsSearch',`
         `contentTag: '#jetsContent'`
            `// columns: [1] // optional, search by first column only`
    `});`

    $('#jetsSearch').on('input', function() {
        jets.update(true);
    });

})`

**Comment by NeXTs** [comment]
Doing .update on `input` may significantly decrease performance because on every key press it explores DOM nodes.
`.update()` should be called only **after** table elements actually change in DOM. For example after full update of table (pages of pagination), after prepending or appending new rows.

**Comment by Lahori-Jawan** [comment]
Yeah, you are right. But I am doing so because once the data is populated, jets attributes are not applied. To make them appear on every row, I update the DOM as soon as input is changed. Do you have other suggestion?

**Comment by NeXTs** [comment]
You should call `.update()` right after data is populated.
Do you have ability to do so?

How you load new data? by clicking some button, by page onload, or some other way?

**Comment by Lahori-Jawan** [comment]
I am using vue router for new pages which acts like single page application. hence no page loads or reloads. just respective components for respective route. also there is a problem. when I load the home page, there is an error in console i.e. Uncaught Error: Error! Could not find searchTag element. when using like so 
`$(document).ready(function() {`
        `var jets = new Jets({`
            `searchTag: '#jetsSearch',`
            `contentTag: '#jetsContent',`        `});`
        `$('#jetsSearch').on('input', function() {`
            `jets.update(true)`
        `});`
`})`
hence jets wouldn't make search in table.
I will try as your suggestion and post the result once I am done with this app.

**Comment by NeXTs** [comment]
`Uncaught Error: Error! Could not find searchTag element`
This may happen because seargTag isn't in DOM yet

`like single page application. hence no page loads or reloads`
okay no problem with that, but there should be some kind of callback/event that triggers right after route loads. or, how you load new data? vue does that? it must have some callback with notification about status of request (was it successful or failed)

**Comment by Lahori-Jawan** [comment]
`callback/event that triggers right after route loads`
I am actually not that expert in vue just yet, thats why I don't know of that but as you say, there must be some mechanism to triggering any action right after route is changed and hence DOM is updated.

`This may happen because searchTag isn't in DOM yet`
yeah, I just checked and it is obvious that searchTag is not present in home page becuase there is no table in home page. So what I could do to prevent this?
If i wait for the document to load, then there is no error but jets doesn't work in this scenario. My failed attempt:
`$(document).on('load', function() {`
        `var jets = new Jets({`
            `searchTag: '#jetsSearch',`
            `contentTag: '#jetsContent',`
        `});`
        `$('#jetsSearch').on('input', function() {`
            `jets.update(true)
        `});`
    `})`

**Comment by NeXTs** [comment]
Jets should be initialized once table is populated on the page. not on dom ready, obviously

So you better ask someone who uses vue. I've never used it )

**Comment by Lahori-Jawan** [comment]
Yeah. I am just checking that. Thanks for your support.

**Comment by Lahori-Jawan** [comment]
ok. I found it. vuejs provides us with `ready: function(){}` method where we can write any third party library which in my case is jQuery. i.e. 
`ready: function(){`
          `var jets = new Jets({`
          `searchTag: '#jetsSearch',`
           `contentTag: '#jetsContent',`
          `});`
          `$('#jetsSearch').on('input', function() {`
              `jets.update(true)`
          `});`
        `}`

now every thing is working just fine.

**Comment by NeXTs** [comment]
👍
