### ISSUE TITLE
Feature: non-selector searchTag

### ISSUE THREAD

**Issue by TrySound** [NeXTs/Jets.js#28]
Would be great to pass instead of selector something like `Element` instance or even search string and then trigger `search` method. Maybe even call `search` with search string as an argument if `searchTag` is not specified. This will reduce dependency on DOM and selectors a bit.

**Comment by NeXTs** [comment]
H Bogdan,

I like this idea.
Try it this way

```
var jets = new Jets({
    contentTag: '.additional-list',
    callSearchManually: true // will not attach event listeners to search element
})

jets.search('search phrase')
```

**Comment by TrySound** [comment]
Thanks a lot!
