### ISSUE TITLE
Работа с несколькими списками

### ISSUE THREAD

**Issue by fdcore** [NeXTs/Jets.js#3]
Сделай пожалуйста работу с несколькими списками, например несколько UL элементов по которым надо делать поиск.

Я конечно сделал кастыль:

```js
_getContentTags: function(query) {
      return Array.prototype.slice.call(document.querySelectorAll(this.content_param + '> *')); 
    },
```

**Comment by Alex-Sokolov** [comment]
А что мешает сделать как в одном из демо, на одно поле поиска навесить нужное количество раз плагин?
```js
  new Jets({
    searchTag: '#additionalListInput',
    contentTag: '#additionalListUl'
  });
  new Jets({
    searchTag: '#additionalListInput',
    contentTag: '#additionalListDiv'
  });
```

**Comment by NeXTs** [comment]
@fdcore Пока можно делать так как показал @Alex-Sokolov, хотя это дублирует event listener'ы.
Я подумаю как бы это получше сделать, пока мысль такая, будут идеи лучше - дайте знать

contentTags: '#additionalListUl, #additionalListDiv'

**Comment by Alex-Sokolov** [comment]
@NeXTs А навешивать не по ID, а на имя класса возможно?

**Comment by NeXTs** [comment]
@Alex-Sokolov так под капотом используется 
```
document.querySelector(opts[param])
```

конечно можно. Можно и по классу и по имени, как угодно.

Кстати спасибо что обратили внимание, у меня совсем вылетело это из головы. Заметил проблему с инициализацией нескольких списков при использовании класса, сегодня поправлю, и именно таким образом и можно будет работать с несколькими списками одновременно.

**Comment by fdcore** [comment]
Пример того что хочу получить http://jsfiddle.net/prdh2j7x/
Атрибут data-jets прописывается только первому списку.

**Comment by NeXTs** [comment]
Дада, я ж написал "Заметил проблему с инициализацией нескольких списков", вечером поправлю

**Comment by NeXTs** [comment]
@fdcore @Alex-Sokolov 

contentTag теперь умеет работать с множественными списками
синтаксис:
contentTag: '.list'
или как в [примере Димы](http://jsfiddle.net/prdh2j7x/) (где дочерних тегов ul много)
contentTag: '#parent ul'
либо
contentTag: 'ul'
и т.д.

**Comment by fdcore** [comment]
@NeXTs спасибо! даже пример на jsfiddle заработал :)

**Comment by NeXTs** [comment]
ага, оно подтянуло новую версию по ссылке
