### ISSUE TITLE
Search in Table but in a specific Column

### ISSUE THREAD

**Issue by scorpionfire** [NeXTs/Jets.js#30]
Can be an idea configure Jets to search in a Table column, deciding the column in the search method.

Example

```javascript
var jets = new Jets({
  searchTag: '#jetsSearch',
  contentTag: '#jetsContent',
  columns: [0,2,5]
});

jets.search("key", [0,5]);
jets.search("key", [0]);
```

**Comment by NeXTs** [comment]
Can you provide an example where this feature may be usable?

**Comment by scorpionfire** [comment]
Sure.
I have this table in my project (with lots more TR)

![image](https://cloud.githubusercontent.com/assets/5221313/22103828/ed86c824-de3c-11e6-975f-5227b795fb95.png)

I add 2 textbox for search, each can be used to search in the respective column.

My idea is:

```javascript
var jets = new Jets({
  contentTag: '#jetsContent',
  callSearchManually: true,
  columns: [0,4]
});

$("#txtSearch1").on("input", function(evt){
  var val=this.value;
  jets.search(val, [0]);
});
$("#txtSearch2").on("input", function(evt){
  var val=this.value;
  jets.search(val, [4]);
});
```

This because I don't want Jets search in all 2 column, but only in the respective column.

**Comment by NeXTs** [comment]
Ok I see
But I'm afraid it's just not possible with current plugin's idea.
It just works in another way. Keywords set during initialization so columns that are available for search may be set only during initialization.

**Comment by scorpionfire** [comment]
And if during initializazion, with new params "searchInSpecificColumn: true", you add more data attribute, for example

``` html
<tr data-jets-cln0="blake norton" data-jets-cln3="31">
  <td >Blake Norton</td>
  <td></td>
  <td></td>
  <td>31</td>
</tr>
```

and when call new search method "jets.search(val, 0)" you generate this css

``` css
#jetsContent > :not([data-jets-cln0 *= "search_query"]){ display:none; }
```
