### ISSUE TITLE
Doesn't work with words with accents (spanish)

### ISSUE THREAD

**Issue by choquo** [NeXTs/Jets.js#31]
Jets.js is amazing, but working on a project i discovered that plugin doesn't works with letters with accents:

"lapiz" and "lápiz" doesn't bring the same results and it will be great if the plugin take the 'á' as a simple 'a' and viceversa.

**Comment by NeXTs** [comment]
Hello, take a look at [this message](https://github.com/NeXTs/Jets.js/issues/4#issuecomment-142714335)

You should provide list of diacritics symbols by yourself, Jets will do the rest

**Comment by NeXTs** [comment]
In your case

`var jets = new Jets({
  searchTag: '#jetsSearch',
  contentTag: '#jetsContent',
  diacriticsMap: {
    a: 'á',
    ...etc 
  }
});`

**Comment by choquo** [comment]
Thank you NeXTs! this works fine!

**Comment by choquo** [comment]
I have tested the diacritisMap with many characters and chrome collapsed the memory, lol, however, i've found another solution from another great plugin (chosen), but this requires modify the jets.js source like this:
```
    replaceDiacritics: function(text) {
      var diacritics = this.options.diacriticsMap;
      for(var letter in diacritics) if(diacritics.hasOwnProperty(letter)) {
        for(var i = 0, ii = diacritics[letter].length; i < ii; i++) {
          text = text.replace(new RegExp(diacritics[letter][i], 'g'), letter);
        }
      }
      //ADD THIS TO FIX SEARCH FOR CHARS WITH ACCENTS/DIACRITICS
      //Taken from: https://github.com/harvesthq/chosen/issues/536
      var specialChars = [
          { val: "a", let: "(Á|À|Ã|Â|Ä|á|à|ã|â|ä|a|A)" },
          { val: "e", let: "(É|È|Ê|Ë|é|è|ê|ë|e|E)" },
          { val: "i", let: "(Í|Ì|Î|Ï|í|ì|î|ï|i|I)" },
          { val: "o", let: "(Ó|Ò|Õ|Ô|Ö|ó|ò|õ|ô|ö|o|O)" },
          { val: "u", let: "(Ú|Ù|Û|Ü|ú|ù|û|ü|u|U)" },
          { val: "c", let: "(Ç|ç|c|C)" }];
      for (var i = 0; i < specialChars.length; i++) {
          text = text.replace(new RegExp(specialChars[i].let, "g"), specialChars[i].val);
          text = text.replace(new RegExp(specialChars[i].val, "g"), specialChars[i].let);
      }
      return text;

    }
```
I think the problem is when Jets it's initialized, it seems like the plugin tries to apply all the regexp to all rows instead of works on "on demand way" only when user types in the input search.

This solution works fine for my needs, and i wanna share this solution if anyone else have the same problem.

**Comment by NeXTs** [comment]
> I have tested the diacritisMap with many characters and chrome collapsed the memory
could you please share this list?

**Comment by choquo** [comment]
Sure, i set up the values this way (with 3500 rows):

```
	diacriticsMap: {
		a: "Á|À|Ã|Â|Ä|á|à|ã|â|ä|a|A",
		e: "É|È|Ê|Ë|é|è|ê|ë|e|E",
		i: "Í|Ì|Î|Ï|í|ì|î|ï|i|I",
		o: "Ó|Ò|Õ|Ô|Ö|ó|ò|õ|ô|ö|o|O",
		u: "Ú|Ù|Û|Ü|ú|ù|û|ü|u|U"
	}
```

**Comment by NeXTs** [comment]
diacriticsMap should not contain `|` symbols and symbols without accents `a|A`, `e|E`, `i|I`, there was example `<>` in [docs](https://jets.js.org/)

It should be written this way
```
diacriticsMap: {
  a: "ÁÀÃÂÄáàãâä",
  e: "ÉÈÊËéèêë",
  i: "ÍÌÎÏíìîï",
  o: "ÓÒÕÔÖóòõôö",
  u: "ÚÙÛÜúùûü"
}
```
http://codepen.io/NeXTs/pen/evMYjM

**Comment by choquo** [comment]
Excellent! setting up the values that way works very well, thank you very much NeXTs!
