### ISSUE TITLE
Do I have to create a new instance of Jets after I delete some items of the list?

### ISSUE THREAD

**Issue by akakoori** [NeXTs/Jets.js#36]
What if I delete the whole list and create a new one (with the same id of course)?

I tried the method `update`, and it didn't work.

**Comment by NeXTs** [comment]
nope, calling `.update` should be enough

could you please provide codepen example?

**Comment by akakoori** [comment]
So I figured out why. Here the `content_tag` is set only once at the time we create a new Jets instance.
```javascript
_getContentTags: function(query) {
      return Array.prototype.slice.call(this.content_tag).reduce(function(all, elem) {
        return all.concat(Array.prototype.slice.call(elem.querySelectorAll(query || ':scope > *')));
      }, []);
    },
```

**Comment by akakoori** [comment]
I have just realized that I don't have to delete the container element, I could keep it!
Sorry for asking a stupid question.. and thank you for your quick reply @NeXTs .
