### ISSUE TITLE
Possibility to search multilevel UL, OL and showing parents

### ISSUE THREAD

**Issue by raineluntta** [NeXTs/Jets.js#38]
Hey,

I was wondering if there's any chance to use this to search multilevel UL and OL, while showing the full path of the search result. Couldn't see anything referencing this use case in the documentation.

For example a list like:

1. Lorem ipsum
2. Dolor sit Amet
    1. Curabitur eu dui eu
    2. Hendrerit egestas
        1. Donec dapibus
    3. Donec ultrices
3. Consectetur adipiscing elit

Searching this list for **dapibus** would then show:

2. Dolor sit Amet
    ii. Hendrerit egestas
            a. Donec dapibus

Thanks in advance!

**Comment by NeXTs** [comment]
Hey

Related issue https://github.com/NeXTs/Jets.js/issues/5

**Comment by raineluntta** [comment]
Thank you for your answer! :) Sad to see there's no way to achieve this. Still a neat way to solve an expensive DOM task! :)
