### ISSUE TITLE
Поддержка диакритических знаков

### ISSUE THREAD

**Issue by Alex-Sokolov** [NeXTs/Jets.js#4]
Есть ли возможность доработать поиск по всем диакритическим знакам? Для русского это удобно, когда в поиске вводишь е и при необходимости ищет и по ё. Или может необязательной опцией сделать хотя бы

Нашёл пример набора символов в другой библиотеке
```js
var DIACRITICS = {
    'a': '[aÀÁÂÃÄÅàáâãäåĀāąĄ]',
    'c': '[cÇçćĆčČ]',
    'd': '[dđĐďĎ]',
    'e': '[eÈÉÊËèéêëěĚĒēęĘ]',
    'i': '[iÌÍÎÏìíîïĪī]',
    'l': '[lłŁ]',
    'n': '[nÑñňŇńŃ]',
    'o': '[oÒÓÔÕÕÖØòóôõöøŌō]',
    'r': '[rřŘ]',
    's': '[sŠšśŚ]',
    't': '[tťŤ]',
    'u': '[uÙÚÛÜùúûüůŮŪū]',
    'y': '[yŸÿýÝ]',
    'z': '[zŽžżŻźŹ]'
};
```

**Comment by NeXTs** [comment]
Привет, я понимаю что это было бы удобно, но боюсь одними лишь селекторами css это сделать трудно

**Comment by Alex-Sokolov** [comment]
Может это опционально сделать, чтобы точечно в настройках плагина при инициализации определять какие диакритические символы искать надо и не потребуется список полный проходить всего. Хотя бы для той же буквы ё добавить и удобнее гораздо станет.

Сейчас же есть возможность в поисковом селекторе AND и OR делать. Разве не подойдет?

**Comment by NeXTs** [comment]
Как я понимаю придется дублировать селекторы для целых слов из-за одного лишь символа. Насколько я помню в css нельзя побуквенно делать OR как например в регулярках, можно только для целых слов, но в этом случае селекторы раздуются до огромных размеров. Если у вас идеи получше покажите прототип на jsfiddle.

**Comment by Alex-Sokolov** [comment]
Может в data-content тогда заносить значения уже без диакритических знаков? Если был в списке пункт с буквой `ё`, то в атрибут поставить `е`. Тогда и в поиске будет оставаться

**Comment by NeXTs** [comment]
Это уже хорошая идея, подумаю над этим

**Comment by NeXTs** [comment]
@Alex-Sokolov, полный список русских диакритических знаков есть?

**Comment by Alex-Sokolov** [comment]
@NeXTs только тот что в первом сообщении, из sifter.js вытащил

**Comment by Alex-Sokolov** [comment]
@NeXTs только `ё` и `й`

**Comment by NeXTs** [comment]
@Alex-Sokolov функционал сделал, хэшмап нужных символов предоставляете сами, синтаксис такой

```
var jets = new Jets({
  searchTag: '#jetsSearch',
  contentTag: '#jetsContent',
  diacriticsMap: {
    е: 'ёèéêëě',
    и: 'йùúûüůŮŪū'
  }
});
```
где ключ - русскоязычный символ на который заменяем, в значении список символов которые заменяем

**Comment by Alex-Sokolov** [comment]
Спасибо!
