### ISSUE TITLE
CSP violation

### ISSUE THREAD

**Issue by Rakshasas** [NeXTs/Jets.js#44]
Wanted to use this library but it violates CSP (Content security policy) because it injects and dynamically manipulates the Style Block.

jets.min.js:9 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src. Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution.

Because changing the style block would recalculate the hash, it's obviously not feasible to make the hash part of the exception for CSP.

**Comment by NeXTs** [comment]
`¯\_(ツ)_/¯`

**Comment by kolappannathan** [comment]
It is possible to achieve this via nonce. I have done it on my site with a modified source code of Jets.js, I'll submit a PR shortly.
