### ISSUE TITLE
custom events

### ISSUE THREAD

**Issue by piehouserat** [NeXTs/Jets.js#6]
Hey, loving this plugin but would love the ability to be able to write custom functions that I tell jets to execute on the following events:

- finished search
- search found no matches

**Comment by Alex-Sokolov** [comment]
Finished search - will be great for attaching another plugins, such as highlighting.

**Comment by Dylan-Chapman** [comment]
Would love the second option. Is there any good way to check for "no matches found" currently that you've found?

**Comment by NeXTs** [comment]
I couldn't find any good CSS-only solution for "no matches" case. This can be done by JS but this will completely break main idea of plugin :\
I'll do it as soon as I will have more free time.

**Comment by piehouserat** [comment]
@Dylan-Chapman so I'm using jets against a table like so:

var jets = new Jets({
  searchTag: '#inventory-search-field',
  contentTag: '#inventory-table-body',
  columns: [1, 2]
});

and then I have this:

$("#inventory-search-field").keyup(function () {
    if (!$('#inventory-table tbody tr:visible').length) {
        $('#inventory-list').hide();
        $('#no-records-found').show();
    }
    else {
        $('#no-records-found').hide();
    }
});

which I can live with for now...

You could easily adapt that to work for div's, ul's etc...

**Comment by NeXTs** [comment]
Hello guys
I've added *didSearch* callback which would return single arguments containing last search phrase, so it may be called by

```
var jets = new Jets({
  searchTag: '#inventory-search-field',
  contentTag: '#inventory-table-body',
  columns: [1, 2],
  didSearch: function(search_phrase) {
    // whatever
  }
});
```

@piehouserat  @Dylan-Chapman Sorry but I decided not to extend the plugin with such functionality yet. Until I find good solution.
For this moment you could use @piehouserat solution to manually check if some visible items exists in the DOM. With new callback function it may be done this way.

```
var jets = new Jets({
  searchTag: '#inventory-search-field',
  contentTag: '#inventory-table-body',
  columns: [1, 2],
  didSearch: function(search_phrase) {
    var hasResults = $('#inventory-table tbody tr:visible').length;
    if ( ! hasResults) {
      //  no results
    } else {
      // has results
    }
  }
});
```
