### ISSUE TITLE
Slowest on latest Safari

### ISSUE THREAD

**Issue by optikfluffel** [NeXTs/Jets.js#8]
Hi, I'm running OS X 10.11.1 Beta and using Safari I get something like this:
![screen shot 2015-10-16 at 15 35 51](https://cloud.githubusercontent.com/assets/379915/10542915/c62924e8-741b-11e5-9afa-5fb98454c9d2.png)
On Firefox and Chrome Jets is still the fastest.

**Comment by NeXTs** [comment]
Cool optimisation, Safari!
Thanks for letting me know.
